GET http://localhost:3001/users HTTP/1.1
Content-Type: application/json


#####


POST http://localhost:3001/users HTTP/1.1
Content-Type: application/json

{
    "firstName": "sundos"
}


#####


PUT http://localhost:3001/users/b63e HTTP/1.1
Content-Type: application/json

{
    "firstName": "Olia"
}


#####


DELETE  http://localhost:3001/users/b63e HTTP/1.1
Content-Type: application/json





